runtime: nodejs14
env: standard
service: default

handlers:
  - url: /static
    static_dir: packages/dapp/build/static

  - url: /(.*\.(json|ico|js))$
    static_files: packages/dapp/build/\1
    upload: packages/dapp/build/.*\.(json|ico|js)$

  - url: .*
    static_files: packages/dapp/build/index.html
    upload: packages/dapp/build/index.html